### ISSUE TITLE
项目很nice，希望能更好。

### ISSUE THREAD

**Issue by CoderST** [BrinedFish0222/flutter_kline#1]
iphone12上运行，在日K用手指在屏幕上快速滑动一下，K线只是在滑动方向滑动一点，没有像列表那样慢慢的减速效果，不知道这个是不是个优化点。

**Comment by BrinedFish0222** [comment]
是的，这是目前K线图很严重的体验问题，后续需要对其进行再次优化

> iphone12上运行，在日K用手指在屏幕上快速滑动一下，K线只是在滑动方向滑动一点，没有像列表那样慢慢的减速效果，不知道这个是不是个优化点。

**Comment by BrinedFish0222** [comment]
> iphone12上运行，在日K用手指在屏幕上快速滑动一下，K线只是在滑动方向滑动一点，没有像列表那样慢慢的减速效果，不知道这个是不是个优化点。

体验问题已在版本2.0.0-beta修复
